###############################################################################################
################                          Introduction                           ##############
###############################################################################################

# This script performs quantification of spot (e.g. FISH) signals and requires the following input:
# * nuclear masks generated by Cellpose from DAPI images (16 bit .png files wherein each mask is assigned a unique grey value)      ! HERE 8 BIT !
# * spot data generated by RS-FISH from spot images (.csv table with spot XY positions and intensities)
# * corresponding DAPI & spot images (maxZ projections)


#########################################################################
##### spot calling script (BATCH MODE) ##################################
#########################################################################

#### Packages and functions ###
library(EBImage)

# specify parent directory of functions
inputfolder <- "insert file path/functions/"
setwd(inputfolder)

source("importSpotData_v01.R")
source("quantNuclei_v01.R")

###############################################################################################
####################          Define input files and folders                     ##############
###############################################################################################

# specify parent directory of input files
inputfolder <- "insert file path/wt/ctrl/bg_and_ff_corrected/"

# specify subdirectories of parent
inputDAPI <- paste0(inputfolder, "405_ffc/")
inputspot <- paste0(inputfolder, "spot/")
inputnucmask <- paste0(inputfolder, "405_ffc/Cellpose/")
inputspotcnt <- paste0(inputfolder, "spot/RSFISH/")

# specify path to DAPI images
dapi_files <- paste0(inputDAPI,list.files(inputDAPI,pattern = "_maxZ.tif$", recursive = TRUE))
# specify path to spot images
spot_files <- paste0(inputspot,list.files(inputspot,pattern = "_maxZ.tif$", recursive = TRUE))
# specify path to nuclear mask .png files (cellpose output)
nucmask_files <- paste0(inputnucmask,list.files(inputnucmask,pattern = "nucmask.tif$", recursive = TRUE))
# specify path to RS-FISH spot count .csv files (RS-FISH output)
spotcount_files <- paste0(inputspotcnt,list.files(inputspotcnt,pattern = "_spots.csv$", recursive = TRUE))

###############################################################################################
####################  Loop over each single well of the list for analysis     #################
###############################################################################################

# timestamp
timestamp <- gsub("-","",gsub(":","",gsub(" ","",substr(Sys.time(),1,19))))

# Check if every well has a matching nucmasks .png file and RS-FISH spot count .csv file
if(length(nucmask_files)!=length(spotcount_files)){print("WARNING: Missing files. Please make sure that every image has a matching nuclear masks file and an RS-FISH spot count file")}

# generate template for results table
results <- data.frame()

# Start well loop
for(m in 1:length(nucmask_files)){

  print(paste0("Processing image: ",nucmask_files[m]))
  start_time <- Sys.time()
  
  ###############################################################################################
  ################### Import nuclear masks from cellpose output .png files ######################
  
  nucmasks <- readImage(nucmask_files[m])
  # In order to work with the masks the pixel values are converted into integer values
  # The background  mask receives the value 0; nuclear masks receive values 1 to n
  nucmasks <-Image(as.numeric(as.factor(nucmasks))-1,dim = dim(nucmasks))
  # Optional checks:
  # *Raw number of nuclear masks
  # max(nucmasks)
  # *Display color-coded nuclear masks for inspection
  # display(colorLabels(nucmasks))
  
  #########################################################################################################################
  ############ Import & assign spot count from the spot channel to the segmented nuclei ###################################
  
  # Import spot data from RS-FISH
  if (file.size(spotcount_files[m]) == 0) {
    results_temp <- data.frame(position=m,cell=1,spot_counts=0,altfish_mean=0,altfish_med=0,altfish_intden=0,altfish_sd=0,dapi_mean=0,dapi_med=0,dapi_intden=0,dapi_sd=0,nuc_spot_intden=0,nuc_spot_minint=0,nuc_spot_maxint=0)
  } else {
    spotData <- read.csv(spotcount_files[m],sep=",")
    
    # Generate spot image where spots are single pixels with value of the spot intensity
    spots <- importSpotData(spotData,nucmasks, norm16bit = TRUE)
    
    # Binarize spot image for counting
    spots_bin <- spots>0
    # Count the number of spots per nucleus
    # This is done by summing up all pixel values in the binary spot image that fall into each nuclear mask region
    # The resulting object is a vector with the spot counts as value and names(vector) = nuc_ids
    spot_counts <- quantNuclei(nucmasks,spots_bin,sum)
    
    # Quantify some spot intensity parameters for each nucleus
    # Quantify integrated spot intensity for each nuclear mask as the sum of all single spot intensities
    nuc_spot_intden <- quantNuclei(nucmasks,spots,sum)
    # Quantify minimum spot intensity in each nuclear mask (the minimum non-zero has to be taken because the background is zero)
    # This will generate Inf values that are set to zero in the subsequent step
    nuc_spot_minint <- quantNuclei(nucmasks,spots,function(x) min(x[x>0]))
    nuc_spot_minint[nuc_spot_minint==Inf] <- 0
    # Quantify maximum spot intensity in each nuclear mask 
    nuc_spot_maxint <- quantNuclei(nucmasks,spots,max)
    
    # EXAMPLE
    # To subset for spots of with certain intensity criteria
    # subset for spots with >15k counts
    # spots_15k <- spots>15000/2^16
    
    ######################################################################################################################
    ###################### * Import of DAPI and RS-FISH maximum projections              #################################
    ###################### * Quantification of image features in the final nuclear masks #################################
    ######################################################################################################################
    
    ### DAPI channel
    # Import DAPI image
    img_dapi <- readImage(dapi_files[m])
    
    # Quantify mean intensity for each nuclear mask
    dapi_mean <- quantNuclei(nucmasks,img_dapi,mean)
    # Quantify sd of intensity for each nuclear mask
    dapi_sd <- quantNuclei(nucmasks,img_dapi,sd)
    # Quantify median intensity for each nuclear mask
    dapi_med <- quantNuclei(nucmasks,img_dapi,median)
    # Quantify integrated intensity for each nuclear mask
    dapi_intden <- quantNuclei(nucmasks,img_dapi,sum)
    
    ### ALT-FISH channel
    # Import ALT-FISH image
    img_altfish <- readImage(spot_files[m])
    
    # Quantify mean intensity for each nuclear mask
    altfish_mean <- quantNuclei(nucmasks,img_altfish,mean)
    # Quantify sd of intensity for each nuclear mask
    altfish_sd <- quantNuclei(nucmasks,img_altfish,sd)
    # Quantify median intensity for each nuclear mask
    altfish_med <- quantNuclei(nucmasks,img_altfish,median)
    # Quantify integrated intensity for each nuclear mask
    altfish_intden <- quantNuclei(nucmasks,img_altfish,sum)
    
    ###############################################################################################################################
    ######################################### Summary and export of results  ######################################################
    
    ##### RESULTS TABLE containing #####
    # *spot assignment
    # *nucleus position & shape features
    # *intensity measurements on nuclear masks (mean, median, intden, sd) in both channels
    
    position <- m
    cell <- seq(1:length(spot_counts))
    results_temp <- cbind(position,cell,spot_counts,altfish_mean,altfish_med,altfish_intden,altfish_sd,dapi_mean,dapi_med,dapi_intden,dapi_sd,nuc_spot_intden,nuc_spot_minint,nuc_spot_maxint)
    
  }
  
  results <- rbind(results,results_temp)
  
  end_time <- Sys.time()
  duration <- end_time - start_time
  print(paste0("Done sample ",m, " of ", length(nucmask_files), ". ", duration))
  
# loop end
}
write.table(results, paste0(inputfolder,"results.csv"),sep = "\t",row.names = FALSE,quote=F)
